// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcnaixizvhafgwoajvrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjbmFpeGl6dmhhZmd3b2FqdnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzQzOTEsImV4cCI6MjA3MjAxMDM5MX0.-l0saemuKGaz_GGzPAT7Yvc9M6eV9ukV9ifoVEzKrmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});